### ISSUE TITLE
More explanation for optimize function

### ISSUE THREAD

**Issue by songyanho** [knightjdr/hclust#1]
Hi,

I would like to know more about the function of `optimize`. Would you mind to explain with examples?

**Comment by knightjdr** [comment]
The purpose of the `Optimize` function is to optimize the leaf ordering. You can find an explanation of this in the paper by [Bar-Joseph](https://academic.oup.com/bioinformatics/article/17/suppl_1/S22/261423). For instance, Fig. 1 shows a simple example of node flipping to change the leaf ordering while maintaining clusters.

**Comment by songyanho** [comment]
Thank you for the information. Can I summaries that optimise function rearrange the leaf so that distance of left leaf is smaller or equal to distance of right leaf?

**Comment by knightjdr** [comment]
You're on the right track. It's the between-leaf distances that are minimized, i.e. to order the leafs so that the sum of the distances between them is minimized.
